move('#box')
    .delay('1s')
    .x(150).y(150)
    .rotate(360)
    .set('background', 'lightgreen')
    .duration('2s')
    .then()
        .scale(1.5)
        .set('background', 'lightpink')
        .set('opacity', 0.6)
        .duration('3s')
        .pop()
    .end() 